// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations, seeding and Studio must reach Postgres directly. A hosted
    // pooler (Neon, Supabase) runs in transaction mode, which cannot carry the
    // session state those operations need. DIRECT_URL is unset locally, where
    // there is one database and no pooler, so this falls back to DATABASE_URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
